version: '3.9'

services:
  cwr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CW-Server
    image: cwr
    ports:
      - "8000:8000"
    environment:
      - GANACHE_URI=http://ganache:8545

  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache-cli
    ports:
      - "8545:8545"
    command: ganache-cli --host 0.0.0.0 --port 8545 --networkId 1337 --defaultBalanceEther 1000
